extend type Query {
  users: [User!]!
  userById(userId: Int!): User @cacheControl(maxAge: 0)
  me: User!
}

extend type Mutation {
  createUser(input: CreateUserInput!): CreateUserPayload!
}

type User {
  id: Int!
  firstName: String!
  lastName: String!
  fullName: String!
  email: String!
}

input CreateUserInput {
  firstName: String!
  lastName: String!
  email: String!
}

type CreateUserPayload {
  user: User
}
