enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  inheritMaxAge: Boolean
  maxAge: Int
  scope: CacheControlScope
) on FIELD_DEFINITION | INTERFACE | OBJECT | UNION

type Query {
  # eslint-disable-next-line
  _empty: String
}

type Mutation {
  # eslint-disable-next-line
  _empty: String
}
