enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type Query {
  _empty: String
  userById(userId: Int!): User @cacheControl(maxAge: 0)
}

type Mutation {
  _empty: String
}
