name: CI

on:
  push:
    branches-ignore: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn test:lint
      - run: yarn test:jest

  schema-validation:
    name: Schema Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:schema-compiled.graphql"
          approve-label: "expected-breaking-change"
